const TOOLTIP_PLACEMENTS = {
  TOP: 'top',
  BOTTOM: 'bottom',
  LEFT: 'left',
  RIGHT: 'right',
} as const;
const TOOLTIP_PLACEMENT_VALUES = Object.values(TOOLTIP_PLACEMENTS);
const DEFAULT_TOOLTIP_PLACEMENT = TOOLTIP_PLACEMENTS.TOP;

const BUTTON_HEADER_POSITIONS = {
  LEFT: 'left',
  RIGHT: 'right',
} as const;
const BUTTON_HEADER_POSITION_VALUES = Object.values(BUTTON_HEADER_POSITIONS);
const DEFAULT_BUTTON_HEADER_POSITION = BUTTON_HEADER_POSITIONS.LEFT;

export {
  TOOLTIP_PLACEMENTS,
  TOOLTIP_PLACEMENT_VALUES,
  DEFAULT_TOOLTIP_PLACEMENT,
  BUTTON_HEADER_POSITIONS,
  BUTTON_HEADER_POSITION_VALUES,
  DEFAULT_BUTTON_HEADER_POSITION,
}